### ISSUE TITLE
stompngo should not panic when parsing headers, return an error instead.

### ISSUE THREAD

**Issue by kelseyhightower** [gmallard/stompngo#12]
While connecting to an Apache Apollo broker I ran into the following:

```
panic: runtime error: index out of range

goroutine 7 [running]:
runtime.panic(0x6292c0, 0x8e4837)
    /usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/gmallard/stompngo.(*Connection).readFrame(0xc210072000, 0xc21000aa60, 0xe, 0x8f2490, 0x0, ...)
    /Users/kelseyhightower/go/src/github.com/gmallard/stompngo/reader.go:122 +0x85e
github.com/gmallard/stompngo.(*Connection).reader(0xc210072000)
    /Users/kelseyhightower/go/src/github.com/gmallard/stompngo/reader.go:36 +0x3a
created by github.com/gmallard/stompngo.Connect
    /Users/kelseyhightower/go/src/github.com/gmallard/stompngo/connect.go:111 +0x7c9
```

The root cause seems to be reading an invalid header during the readFrame() method:

``` Golang
s = s[0 : len(s)-1]
p := strings.SplitN(s, ":", 2)
if c.Protocol() != SPL_10 && f.Command != CONNECTED {
  p[0] = decode(p[0])
  p[1] = decode(p[1])
}
```

which leads to 

```
panic: runtime error: index out of range
```

I'm thinking we need to do some bounds checking here, and return a custom error message regrading the invalid headers. I'm happy to work on this if you think this is the right direction to go.

**Comment by gmallard** [comment]
If you are still using the stompngo package please try the current v.1.0.2 tag.

Tag information:

b1f1d966dd7b4c6e07278089c658aef2fb44749d refs/tags/v1.0.2

Document that version number in any issue reports.

Thanks for the support.

Guy
