### ISSUE TITLE
Send returns no error after broker drops connection

### ISSUE THREAD

**Issue by andrewzeneski** [gmallard/stompngo#16]
The first attempt to send after a broker drops the connection returns no [expected] error. Subsequent attempts to send will return an expected error.

**Comment by gmallard** [comment]
If you are still using the stompngo package please try the current v.1.0.2 tag.

Tag information:

b1f1d966dd7b4c6e07278089c658aef2fb44749d refs/tags/v1.0.2

Document that version number in any issue reports.

Thanks for the support.

Guy
