### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by dorseydick** [gmallard/stompngo#17]
It would be great if there was a way to connect via SSL. We're using stomp+ssl over port 61613, not regular tcp so unfortunately we can't use this at the moment.

**Comment by gmallard** [comment]
If you are still using the stompngo package please try the current v.1.0.2 tag.

Tag information:

b1f1d966dd7b4c6e07278089c658aef2fb44749d refs/tags/v1.0.2

Document that version number in any issue reports.

Thanks for the support.

Guy
