### ISSUE TITLE
Race in disconnect

### ISSUE THREAD

**Issue by serbaut** [gmallard/stompngo#27]
Disconnect can block forever on line https://github.com/gmallard/stompngo/blob/dev/disconnect.go#L69 if the reader is shutdown before the disconnect receipt has been read.

This can be shown by adding a sleep in reader (TestDiscRace will hang):

    diff --git a/conndisc_test.go b/conndisc_test.go
    index 1e5527d..bc95097 100644
    --- a/conndisc_test.go
    +++ b/conndisc_test.go
    @@ -306,3 +306,22 @@ func TestConnRespData(t *testing.T) {
                    }
            }
     }
    +
    +func TestDiscRace(t *testing.T) {
    +       t.Parallel()
    +       n, _ := openConn(t)
    +       ch := check11(TEST_HEADERS)
    +       c, _ := Connect(n, ch)
    +
    +       r := "my-receipt-001"
    +       e := c.Send(Headers{"destination", "my-dest", "receipt", r},
    +               "my-data")
    +       if e != nil {
    +               t.Errorf("Send: got error %v\n", e)
    +       }
    +       _ = <-c.MessageData
    +
    +       _ = c.Disconnect(empty_headers)
    +       _ = closeConn(t, n)
    +
    +}
    diff --git a/reader.go b/reader.go
    index 46ecc58..3ce0f60 100644
    --- a/reader.go
    +++ b/reader.go
    @@ -60,6 +60,8 @@ func (c *Connection) reader() {

                    c.log("RECEIVE", m.Command, m.Headers)

    +               time.Sleep(time.Second)
    +
                    select {
                    case q = <-c.rsd:
                    default:

Suggested fix: shut down the reader later or close the input channel when the reader exits. or both.

**Comment by gmallard** [comment]
Merged, see:

6401ad7

Several other fixes for race conditions also recently been committed to master.  Please upgrade to at least HEAD of current master : a488ae2

**Comment by gmallard** [comment]
If you are still using the stompngo package please try the current v.1.0.2 tag.

Tag information:

b1f1d966dd7b4c6e07278089c658aef2fb44749d refs/tags/v1.0.2

Document that version number in any issue reports.

Thanks for the support.

Guy

**Comment by serbaut** [comment]
Thanks I will!
