### ISSUE TITLE
Go get fetching the go1 branch

### ISSUE THREAD

**Issue by szank** [gmallard/stompngo#29]
Hi, by default github and godoc are displaying the master branch as default, but when calling `go get github.com/gmallard/stompngo` a `go1` branch is downloaded. 

Which branch should I use? Master seems more reasonable, the missing constants in the go1 branch  like `HK_DESTINATION` are annoying.

**Comment by gmallard** [comment]
Use master.  Or dev for a little more bleeding edge.

I have not merged into the go1 branch in a long time.  Do not use it,
sorry for the confusion.

I need to keep up with the go1 branch ..... or maybe just delete it.

Regards, Guy

**Comment by szank** [comment]
Is there any way to fix the `go get` behaviour? 
I am not even sure if it is a problem with this particular repo or with the `go get` tool itself

**Comment by gmallard** [comment]
When you first did the go get, what commit SHA was checked out?

**Comment by szank** [comment]
```
$ ~/work/go/src/github.com $ go get github.com/gmallard/stompngo
$ ~/work/go/src/github.com $ cd gmallard/stompngo/
$ ~/work/go/src/github.com/gmallard/stompngo $ git log -n2
commit b1f1d966dd7b4c6e07278089c658aef2fb44749d
Merge: a488ae2 42ac5b1
Author: gmallard <allard.guy.m@gmail.com>
Date:   Mon Jul 4 22:23:17 2016 -0400

    Version v1.0.2.  Commit list:

    * dev:
      Bump version to v1.0.2.
      Help stomp 1.0 users that subscribe without a sub ID.
      Add subscription data area, which:
      Relax locking strategy for subscription locks.
      Correct variable typo.
      Add NMSGS to supported environment variables.
      Add STOMP_DEST to supported environment variables.
      Move environment get logic to individual methods.
      Enhange stompngo environment variable helper.
      Copyright date updates.
      Start next version work.
```

**Comment by gmallard** [comment]
Thanks.  I think this has to do with that commit being where the 'go1'
branch is.  I think the go get functionality treats that name
'specially'.  And I had forgotten that.

So it is related to .... both the get tool and this particular repo.

I just replicated what you saw.  Give me a few minutes, I will fix
that.  And ping you back when done.

**Comment by gmallard** [comment]
OK, fixed.  Do me a favor please.  Totally remove the stompngo source
directory.  And redo the 'go get' from the beginning.

You should have an up to date checkout.  Let me know please.


Regards, Guy

**Comment by szank** [comment]
Yep, still fetching `go1`, but the branch is up to date. 
Solved, thanks ! 

Regards, 
Maciej

**Comment by gmallard** [comment]
Yes, the go1 branch will be there.  As a 'remote' branch.  But the 'get'
checkout should be right.

I had the same problems in the stompngo_examples project.  And also
fixed that:

https://github.com/gmallard/stompngo_examples

if you need to take a look it it.

Regards, Guy

**Comment by gmallard** [comment]
Thanks.  A good reminder to me to pay attention to the go1 branch.
