### ISSUE TITLE
Abstract Connection to an interface

### ISSUE THREAD

**Issue by JELGT2011** [gmallard/stompngo#33]
Apologies if this has already been suggested or if this is not the proper channel for suggesting feature requests.  Also, I'm totally willing to make this PR myself, I just want to see how the authors feel about it before actually going about making the code changes.

Abstract `stompngo.Connection` to an interface to allow mock generators to mock the connection and allow for easier testing.  Use a different name to not break backwards compatibility.  So something like:

```go
type STOMPConnection interface {
	Send(stompngo.Headers, string) error
	Connected() bool
	Disconnect(headers stompngo.Headers) error
	Subscribe(headers stompngo.Headers) (<-chan stompngo.MessageData, error)
	Unsubscribe(headers stompngo.Headers) error
	Ack(headers stompngo.Headers) error
	Nack(headers stompngo.Headers) error
}
```

**Comment by gmallard** [comment]
There are no objections to this , at least in concept.

Please pursue this yourself, and submit a PR when complete.

Please add:

```
    Begin(...) ....
    Commit(...)...
    Abort(...)...
```

to the interface.

This package currently does not mock anything in tests.  It depends on the availability of a running message broker.

Therefore, some actual mock tests would also be required in the PR.

Given the general theme of go interfaces I was thinking STOMPConnector for the interface name.  But I can go either way on that.

Rule One:  no external dependencies other than stdlib in the main package.  Adding external dependencies to tests would be accepted assuming those dependencies appear to be stable and well supported.

Rule Two:  try to use idiomatic variable names.  Keep them short.

I can be flexible about rule two.  Rule one, not so much.

Ask other questions at any time.

**Comment by gmallard** [comment]
See: 5d91fde
