### ISSUE TITLE
Panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by sybrandy** [gmallard/stompngo#34]
I don't know why this occurred, but I got this error during one of my test runs:

    panic: non-positive interval for NewTicker
    time.NewTicker
        go/src/time/tick.go:32
    github.com/gmallard/stompngo.(*Connection).receiveTicker
        src/github.com/gmallard/stompngo/heartbeats.go:163
    github.com/gmallard/stompngo.(*Connection).initializeHeartBeats
        src/github.com/gmallard/stompngo/heartbeats.go:183

It only happened to me once, so it's probably something transient.  Just wanted to report it as this seems like something that would be very simple to check for so that it's prevented in the future.

**Comment by gmallard** [comment]
Bizarre.  Was the ticker at 500ms ?

I can see how it could happen.  I will make that code a bit more defensive.

**Comment by gmallard** [comment]
On DEV: 7c54f33

**Comment by sybrandy** [comment]
Honestly, I don't recall.  I waited until I was done testing to file the bug as I was focused on trying to figure out other issues.

The fix, however, looks good.
