### ISSUE TITLE
Is this a potential bug of SetWriteDeadline? 

### ISSUE THREAD

**Issue by itomsawyer** [gmallard/stompngo#38]
Hi , I have read the source code of stompngo and find something hard to understand.

Here's a reader go routine  which can be set read timeout by conn.ReadDealLine

```
func (c *Connection) setReadDeadline() {
	if c.dld.rde && c.dld.rds {
		_ = c.netconn.SetReadDeadline(time.Now().Add(c.dld.rdld))
	}
}
```

The reader use c.dld.rde && c.dld.rds to check if read deadline will be set.
Buf a writer use c.dld.wde && c.dld.dns to check if write deadline will be set. 
Should it use c.dld.wde && c.dld.wds instead ? 

```
func (c *Connection) wireWrite(d wiredata) {
	f := &d.frame
	// fmt.Printf("WWD01 f:[%v]\n", f)
	switch f.Command {
	case "\n": // HeartBeat frame
		if c.dld.wde && c.dld.dns {
			_ = c.netconn.SetWriteDeadline(time.Now().Add(c.dld.wdld))
		}
```

Looking forward to your reply

**Comment by gmallard** [comment]
Agreed, it is  bug.

Repeated numerous times in writer.go.

If you give me a PR, I will accept it.

Watch line 242, it requires some extra care.

**Comment by itomsawyer** [comment]
@gmallard new pull request has been submitted, plz check it out

**Comment by gmallard** [comment]
Closing this per:

cc91367

cc91367
