### ISSUE TITLE
Question about heartbeats

### ISSUE THREAD

**Issue by c-bg** [gmallard/stompngo#48]
Hi, 
Thanks a lot for this really nice library :) 
I've got a small question. 
Do I understand correctly that the library automatically takes care of heart-beating? 
For example, in the [documentation](https://godoc.org/github.com/gmallard/stompngo#Connection.Disconnect) of `Disconnect`, it says

> Disconnect from a STOMP broker.
> 
> Shut down heart beats if necessary. Set connection status to false to disable further actions with this connection. 

Is the "Shut down" meant as an imperative or a description of what the function does? ("Disconnect" in the first sentence seems to be a description, so I'm not sure) 

Thanks a lot for your help in advance!

**Comment by gmallard** [comment]
Yes, the library takes care of heart-beating *if* you request heartbeats on CONNECT, and *if* the broker supports them.

The library is strictly compliant with the STOMP specification.  For more on heartbeats, see:

https://stomp.github.io/stomp-specification-1.2.html#Heart-beating

And also:

https://github.com/gmallard/stompngo/blob/dev/heartbeats.go

Heartbeat support is implemented in individual go routines, hence the need for "shutdown".

Let me know if there are further questions.

**Comment by c-bg** [comment]
Thanks a lot for the helpful reply! :)
