### ISSUE TITLE
Lack of detection of EOF (No automatic reconnection)

### ISSUE THREAD

**Issue by sigmonsays** [gmallard/stompngo#5]
Not sure how reconnection or detection of failed network connections is supposed to work.. .but...

reader.go contains a bug in which it does not properly detect EOF. 

This may be by design, however if you close(c) after the for {} loop, the user and use the coma, ok ("msg, ok := <-r") pattern to detect when the channel is closed and attempt a reconnect.

The fix is to close the input channel which will signal a closed channel to the receiver.

~ line 70 of   func (c *Connection) reader() {

 70     fmt.Println("Dead connection")
 71     close(c.input)

Reconnection could be made automatic but it might be up to the caller to handle this also.

**Comment by gmallard** [comment]
If you are still using the stompngo package please try the current v.1.0.2 tag.

Tag information:

b1f1d966dd7b4c6e07278089c658aef2fb44749d refs/tags/v1.0.2

Document that version number in any issue reports.

Thanks for the support.

Guy
